export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const HOME_INDEX_GET_CATEGORIES_SUCCESS = 'HOME_INDEX_GET_CATEGORIES_SUCCESS'
export const HOME_INDEX_GET_LISTS_SUCCESS = 'HOME_INDEX_GET_LISTS_SUCCESS'
export const HOME_INDEX_GET_COUNTS_SUCCESS = 'HOME_INDEX_GET_COUNTS_SUCCESS'
export const HOME_INDEX_SIDE_AD_GET_ENTITY_SUCCESS = 'HOME_INDEX_SIDE_AD_GET_ENTITY_SUCCESS'
export const HOME_INDEX_SIDE_TOPIC_GET_LISTS_SUCCESS = 'HOME_INDEX_SIDE_TOPIC_GET_LISTS_SUCCESS'
export const HOME_INDEX_SIDE_LINK_GET_LISTS_SUCCESS = 'HOME_INDEX_SIDE_LINK_GET_LISTS_SUCCESS'

// AUTH
export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED'
// Register
export const ACCOUNT_REGISTER_INIT = 'ACCOUNT_REGISTER_INIT'
export const ACCOUNT_REGISTER_SUBMIT_SUCCESS = 'ACCOUNT_REGISTER_SUBMIT_SUCCESS'
export const ACCOUNT_REGISTER_SUBMIT_FAILURE = 'ACCOUNT_REGISTER_SUBMIT_FAILURE'
// Login
export const ACCOUNT_LOGIN_INIT = 'ACCOUNT_LOGIN_INIT'
export const ACCOUNT_LOGIN_SUBMIT_SUCCESS = 'ACCOUNT_LOGIN_SUBMIT_SUCCESS'
export const ACCOUNT_LOGIN_SUBMIT_FAILURE = 'ACCOUNT_LOGIN_SUBMIT_FAILURE'
// Logout
export const ACCOUNT_LOGOUT_INIT = 'ACCOUNT_LOGOUT_INIT'
export const ACCOUNT_LOGOUT_SUBMIT_SUCCESS = 'ACCOUNT_LOGOUT_SUBMIT_SUCCESS'
export const ACCOUNT_LOGOUT_SUBMIT_FAILURE = 'ACCOUNT_LOGOUT_SUBMIT_FAILURE'
// Settings
export const ACCOUNT_SETTINGS_PROFILE_SUBMIT_SUCCESS = 'ACCOUNT_SETTINGS_PROFILE_SUBMIT_SUCCESS'
export const ACCOUNT_SETTINGS_PROFILE_SUBMIT_FAILURE = 'ACCOUNT_SETTINGS_PROFILE_SUBMIT_FAILURE'
export const ACCOUNT_SETTINGS_PASSWORD_SUBMIT_SUCCESS = 'ACCOUNT_SETTINGS_PASSWORD_SUBMIT_SUCCESS'
export const ACCOUNT_SETTINGS_PASSWORD_SUBMIT_FAILURE = 'ACCOUNT_SETTINGS_PASSWORD_SUBMIT_FAILURE'
export const ACCOUNT_SETTINGS_NOTIFICATION_SUBMIT_SUCCESS = 'ACCOUNT_SETTINGS_NOTIFICATION_SUBMIT_SUCCESS'
export const ACCOUNT_SETTINGS_NOTIFICATION_SUBMIT_FAILURE = 'ACCOUNT_SETTINGS_NOTIFICATION_SUBMIT_FAILURE'

export const CATEGORY_INDEX_GET_CATEGORIES_SUCCESS = 'CATEGORY_INDEX_GET_CATEGORIES_SUCCESS'
export const CATEGORY_INDEX_GET_LISTS_SUCCESS = 'CATEGORY_INDEX_GET_LISTS_SUCCESS'

export const USER_DETAIL_GET_DATA_SUCCESS = 'USER_DETAIL_GET_DATA_SUCCESS'
export const USER_DETAIL_GET_LISTS_SUCCESS = 'USER_DETAIL_GET_LISTS_SUCCESS'

export const TOPIC_INDEX_GET_DATA_SUCCESS = 'TOPIC_INDEX_GET_DATA_SUCCESS'
export const TOPIC_INDEX_GET_LISTS_SUCCESS = 'TOPIC_INDEX_GET_LISTS_SUCCESS'
// 新建主题
export const TOPIC_CREATE_INIT = 'TOPIC_CREATE_INIT'
export const TOPIC_CREATE_INIT_GET_CATEGORIES_SUCCESS = 'TOPIC_CREATE_INIT_GET_CATEGORIES_SUCCESS'
export const TOPIC_CREATE_SUBMIT_SUCCESS = 'TOPIC_CREATE_SUBMIT_SUCCESS'
export const TOPIC_CREATE_SUBMIT_FAILURE = 'TOPIC_CREATE_SUBMIT_FAILURE'
// 编辑主题
export const TOPIC_EDIT_INIT = 'TOPIC_EDIT_INIT'
export const TOPIC_EDIT_INIT_GET_CATEGORIES_SUCCESS = 'TOPIC_EDIT_INIT_GET_CATEGORIES_SUCCESS'
export const TOPIC_EDIT_INIT_GET_DATA_SUCCESS = 'TOPIC_EDIT_INIT_GET_DATA_SUCCESS'
export const TOPIC_EDIT_SUBMIT_SUCCESS = 'TOPIC_EDIT_SUBMIT_SUCCESS'
export const TOPIC_EDIT_SUBMIT_FAILURE = 'TOPIC_EDIT_SUBMIT_FAILURE'
// 主题详情
export const TOPIC_DETAIL_GET_DATA_SUCCESS = 'TOPIC_DETAIL_GET_DATA_SUCCESS'
export const TOPIC_DETAIL_GET_LISTS_SUCCESS = 'TOPIC_DETAIL_GET_LISTS_SUCCESS'
export const TOPIC_DETAIL_SUBSCRIBE_SUCCESS = 'TOPIC_DETAIL_SUBSCRIBE_SUCCESS'
export const TOPIC_DETAIL_SUBSCRIBE_FAILURE = 'TOPIC_DETAIL_SUBSCRIBE_FAILURE'

// Article Create
export const ARTICLE_CREATE_INIT = 'ARTICLE_CREATE_INIT'
export const ARTICLE_CREATE_INIT_GET_OWNTOPICS_SUCCESS = 'ARTICLE_CREATE_INIT_GET_OWNTOPICS_SUCCESS'
export const ARTICLE_CREATE_SUBMIT_SUCCESS = 'ARTICLE_CREATE_SUBMIT_SUCCESS'
export const ARTICLE_CREATE_SUBMIT_FAILURE = 'ARTICLE_CREATE_SUBMIT_FAILURE'
export const ARTICLE_EDIT_INIT = 'ARTICLE_EDIT_INIT'
export const ARTICLE_EDIT_INIT_GET_OWNTOPICS_SUCCESS = 'ARTICLE_EDIT_INIT_GET_OWNTOPICS_SUCCESS'
export const ARTICLE_EDIT_INIT_GET_DATA_SUCCESS = 'ARTICLE_EDIT_INIT_GET_DATA_SUCCESS'
export const ARTICLE_EDIT_SUBMIT_SUCCESS = 'ARTICLE_EDIT_SUBMIT_SUCCESS'
export const ARTICLE_EDIT_SUBMIT_FAILURE = 'ARTICLE_EDIT_SUBMIT_FAILURE'
export const ARTICLE_DETAIL_GET_DATA_SUCCESS = 'ARTICLE_DETAIL_GET_DATA_SUCCESS'
export const ARTICLE_DETAIL_GET_LISTS_SUCCESS = 'ARTICLE_DETAIL_GET_LISTS_SUCCESS'
export const ARTICLE_DETAIL_COMMENT_SUCCESS = 'ARTICLE_DETAIL_COMMENT_SUCCESS'
export const ARTICLE_DETAIL_COMMENT_FAILURE = 'ARTICLE_DETAIL_COMMENT_FAILURE'
export const ARTICLE_DETAIL_UPVOTE_SUCCESS = 'ARTICLE_DETAIL_UPVOTE_SUCCESS'
export const ARTICLE_DETAIL_UPVOTE_FAILURE = 'ARTICLE_DETAIL_UPVOTE_FAILURE'
export const ARTICLE_DETAIL_TOPIC_SUBSCRIBE_SUCCESS = 'ARTICLE_DETAIL_TOPIC_SUBSCRIBE_SUCCESS'
export const ARTICLE_DETAIL_TOPIC_SUBSCRIBE_FAILURE = 'ARTICLE_DETAIL_TOPIC_SUBSCRIBE_FAILURE'

export const TAG_DETAIL_GET_DATA_SUCCESS = 'TAG_DETAIL_GET_DATA_SUCCESS'
export const TAG_DETAIL_GET_LISTS_SUCCESS = 'TAG_DETAIL_GET_LISTS_SUCCESS'

export const NOTIFICATION_COUNTS_INIT = 'NOTIFICATION_COUNTS_INIT'
export const NOTIFICATION_COUNTS_GET_DATA_SUCCESS = 'NOTIFICATION_COUNTS_GET_DATA_SUCCESS'
export const NOTIFICATION_INDEX_GET_LISTS_SUCCESS = 'NOTIFICATION_INDEX_GET_LISTS_SUCCESS'
export const NOTIFICATION_GET_ENTITY_SUCCESS = 'NOTIFICATION_GET_ENTITY_SUCCESS'

export const ASSET_PICKER_GET_LISTS_SUCCESS = 'ASSET_PICKER_GET_LISTS_SUCCESS'
export const ASSET_PICKER_SUBMIT_SUCCESS = 'ASSET_PICKER_SUBMIT_SUCCESS'
export const ASSET_PICKER_SUBMIT_FAILURE = 'ASSET_PICKER_SUBMIT_FAILURE'

export const SEARCH_USER_GET_LISTS_SUCCESS = 'SEARCH_USER_GET_LISTS_SUCCESS'
export const SEARCH_TOPIC_GET_LISTS_SUCCESS = 'SEARCH_TOPIC_GET_LISTS_SUCCESS'
export const SEARCH_ARTICLE_GET_LISTS_SUCCESS = 'SEARCH_ARTICLE_GET_LISTS_SUCCESS'

export const QINIU_GET_TOKEN_SUCCESS = 'QINIU_GET_TOKEN_SUCCESS'
